version: '3'

services:
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - photic
    restart: unless-stopped

  web:
    build:
      context: .

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ${ROI_PATH}:/rois
    depends_on:
      - db
    networks:
      - photic
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ${ROI_PATH}:/rois
      - ${SSL_KEY}:/ssl/ssl.key:ro
      - ${SSL_CERT}:/ssl/ssl.cer:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - photic
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  photic:
    name: photic
    driver: bridge
