version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=photic
      - POSTGRES_USER=photic
      - POSTGRES_PASSWORD=photic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - photic

  web:
    build:
      context: .
      args:
        HTTP_PROXY: '${HTTP_PROXY}'
        HTTPS_PROXY: '${HTTPS_PROXY}'

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ../Photic-ROIs:/rois
    depends_on:
      - db
    networks:
      - photic

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./static:/code/static
      - ../Photic-ROIs:/rois
    ports:
      - "${HOST:-0.0.0.0}:${HTTP_PORT:-80}:80"
    depends_on:
      - web
    networks:
      - photic

volumes:
  postgres_data:

networks:
    photic:
      name: photic
      driver: bridge
