version: '3'

services:
  db:
    image: postgres:${POSTGRES_TAG:-12-alpine}
    environment:
      - POSTGRES_DB=photic
      - POSTGRES_USER=photic
      - POSTGRES_PASSWORD=photic
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - photic

  web:
    build:
      context: .
      args:
        HTTP_PROXY: '${HTTP_PROXY}'
        HTTPS_PROXY: '${HTTPS_PROXY}'

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ${ROI_PATH}:/rois
    depends_on:
      - db
    networks:
      - photic

  nginx:
    image: nginx:alpine
    environment:
      - NGINX_HOST=${HOST}
      - NGINX_HTTP_PORT=${HTTP_PORT}
      - NGINX_HTTPS_PORT=${HTTPS_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./static:/code/static
      - ${ROI_PATH}:/rois
      - ${SSL_KEY}:/ssl/ssl.key:ro
      - ${SSL_CERT}:/ssl/ssl.cer:ro
      - ./logs:/var/log/nginx
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    depends_on:
      - web
    networks:
      - photic

volumes:
  postgres_data:

networks:
    photic:
      name: ${DOCKER_NETWORK}
      driver: bridge
