version: '3.9'

services:
  web:
    image: harbor-registry.whoi.edu/photic/photic_web:1.0
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${ROI_PATH}:/rois
      - static-files:/app/static
      - ./local_settings.py:/app/photic/local_settings.py:ro
    networks:
      - photic
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_TAG:-12-alpine}
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - photic
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CERT}:/ssl/ssl.cer:ro
      - ${SSL_KEY}:/ssl/ssl.key:ro
      - static-files:/app/static:ro
      - ${ROI_PATH}:/rois
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - photic
    restart: unless-stopped

volumes:
  static-files:
  nginx-config:


networks:
  photic:
    name: photic
    driver: bridge
