# Generated by Django 3.1.6 on 2021-02-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210205_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='roi_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
