# Generated by Django 3.1.7 on 2021-03-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210208_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
