# Generated by Django 3.1.7 on 2021-03-31 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_label_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='winning_annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_roi', to='core.annotation'),
        ),
    ]
