# Generated by Django 5.2.3 on 2025-08-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_roi_winning_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roi',
            name='origin',
            field=models.CharField(choices=[('LOCAL', 'local'), ('S3', 's3')], default='local', max_length=50),
        ),
    ]
