# Generated by Django 4.0.5 on 2022-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_roi_winning_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='classifier',
            field=models.TextField(blank=True),
        ),
    ]
