version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to npm against the `develop` branch
    target-branch: "origin/dependabot_fixes"
    # Labels on pull requests for version updates only
    labels:
      - "pip dependencies"